<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Fundamentos: Manejo de Errores</title>
</head>

<body>
  <script>
    // Try, Catch, Finally
    // try {
    //   console.log("En el try se agrega el codigo a evaluar")
    //   noExiste;
    //   console.log("Segundo mensaje en el try")
    // } catch (error) {
    //   console.log("Catch captura cualquier error surgido o lanzado en el try")
    //   console.log(error)
    // } finally {
    //   console.log("el bloque finally se ejecutara siempre al final de un bloque  try-catch")
    // }

    try{
      let numero = "y";
      if(isNaN(numero)){
        throw new Error("No es un numero")
      }

      console.log(numero * numero)
    }
    catch (error) {
      console.log(`Se produjo el siguiente error: ${error}`)
    }
  </script>


</body>

</html>